# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20170605_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='archivo',
            new_name='imagen',
        ),
    ]
